### PR TITLE
Fix ScanForModules_MemoryWalk_Hidden and add new .NET structure scan.

### LINKED ISSUE #234: [Improvement] ScanForModules does not support managed modules
title

### PR DESCRIPTION
**Pull request by gsuberland**
The memory walk check was broken because it assumed that memory regions would be executable. It also started at the wrong address - AllocationBase is the start of the allocator region, whereas BaseAddress is the actual start of the region. This has now been fixed.

This commit also adds a new check, which scans for memory structures that the .NET runtime creates to track loaded modules. This should catch injected modules even if they're dynamically loaded from memory.

This fixes #234 and #237.

### CODE REVIEW

File: al-khaser/AntiDebug/ScanForModules.cpp [hunk 1]
```diff
@@ -342,12 +342,14 @@ BOOL ScanForModules_MemoryWalk_Hidden()
...
-					(region->Protect & PAGE_EXECUTE_WRITECOPY) == PAGE_EXECUTE_WRITECOPY ||
-					(region->Protect & PAGE_EXECUTE_READWRITE) == PAGE_EXECUTE_READWRITE)
+				if ((region->State & MEM_COMMIT) == MEM_COMMIT &&
+					((region->Protect == PAGE_READONLY) ||
+					(region->Protect == PAGE_READWRITE) || 
+					(region->Protect == PAGE_EXECUTE_READ) || 
+					(region->Protect == PAGE_EXECUTE_READWRITE) || 
+					(region->Protect == PAGE_EXECUTE_WRITECOPY)))
 				{
-					auto moduleData = static_cast<PBYTE>(region->AllocationBase);
```
Comment (LordNoteworthy) [inline al-khaser/AntiDebug/ScanForModules.cpp:350]: Nice catch !

File: al-khaser/AntiDebug/ScanForModules.cpp [hunk 2]
```diff
@@ -408,6 +410,90 @@ BOOL ScanForModules_MemoryWalk_Hidden()
 	return anyBadLibs ? TRUE : FALSE;
 }
 
+BOOL ScanForModules_DotNetModuleStructures()
```
Comment (LordNoteworthy) [inline al-khaser/AntiDebug/ScanForModules.cpp:413]: Looks solid.

**Review by LordNoteworthy — APPROVED** [review]
